version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sacadb
      POSTGRES_USER: sacauser
      POSTGRES_PASSWORD: sacapass
    ports:
      - '5432:5432'
